---
.travis.yml:
  rubygems_api_key: "oulIW276p2do5aARC/ghWO5+iHpUi8it4a8DNX+DV3IU4oBgrug5vsU5FJKi9l7kjXG5VBrY8xUPu3ntgGODoT336rOxsvLNUcyaNSTWbRc1Une/iiFKkDPibVmx0DBp6jmshy1OnJYtJ3AbPSYgtjaq4hXEeSMXlVM0GIziul8="
