language: ruby
sudo: false
cache: bundler
script:
- bundle exec rake spec
rvm:
- 1.8.7
- 1.9.3
- 2.0.0
- 2.1.5
matrix:
  fast_finish: true
deploy:
  provider: rubygems
  api_key:
    secure: mA5d/yEuYsdm2A0brLWhEFLzIHAM6rcbYU5CrhloqaaahLN11OleAzF+zEh6VZiSoz/yH5DuIQO3T4NF8UHz0WWVjaih57kxgXffA6ATbYrzZLZovmOJ/CodYlmMMJKD5OTngsPjLyTXgWsAMLEGf6bhYpz+xiN4xbOvGjS2Md0=
  on:
    rvm: 2.1.5
    tags: true
    all_branches: true
notifications:
  email: false
